name: Update Cloudflare TXT Record

on:
  workflow_dispatch:

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Cloudflare TXT Record
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_KEY }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_RECORD_ID: ${{ secrets.CF_RECORD_ID }}
        CF_NAME: ${{ secrets.CF_NAME }}
      run: |
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/dns_records/${CF_RECORD_ID}" \                                     
        -H "Authorization: Bearer ${CF_API_TOKEN}" \
        -H "Content-Type: application/json" \
        --data '{"type":"TXT","name":"${CF_NAME}","content":"test","ttl":120,"proxied":false}'
